### ISSUE TITLE
Windows 10 Master Task Sequence - Mouse Enab

### ISSUE THREAD

**Issue by hkystar35** [winadminsdotorg/SystemCenterConfigMgr#11]
In the "Windows" Group
Step: Disable Mouse Cursor Surpression

Command line reads:
reg import ".\Registry_Windows10\DisableMouseCursorSu**r**pression.reg"

Should read:
reg import ".\Registry_Windows10\DisableMouseCursorSupression.reg"

There's an errant letter "R" in the word Supression that causes the line to fail.
Technically, the word should read "Sup**p**ression", but I'm not too picky so long as it works. :)
(Renaming the files would be a pain, too.)

Thank you!

https://github.com/winadminsdotorg/SystemCenterConfigMgr/blob/master/OSD/Task%20Sequences/Deployment%20Task%20Sequences/Win10MasterDeployment.zip

**Comment by Ebag333** [comment]
Should be resolved in latest TS (modular).
