### ISSUE TITLE
OSD Modular TS In Place update Copy CMTrace error

### ISSUE THREAD

**Issue by ersatyle** [winadminsdotorg/SystemCenterConfigMgr#27]
during an in place upgrade the step Copy CMTrace to staging (xcopy x:\sms\bin\x64\CMTrace.exe %_SMSTSMDataPath% won't happen as there is no x:\ at this point.
then the following Copy CMTrace to Windows System32 will error out as there is not cmtrace in %__SMSTSMDataPath% .
This is in the main OSD - Modular OSD.
![image](https://user-images.githubusercontent.com/21692877/38383432-82827fce-38da-11e8-8a5f-ae4f425f4b63.png)

**Comment by RowdyChildren** [comment]
Suggesting marking this as won't fix and removing the step all together because the client is now coppied down automatically as of SCCM 1806

**Comment by Ebag333** [comment]
And (finally) done.
