### ISSUE TITLE
OSD - Modular TS Logs file upon failure doesn't contain computername

### ISSUE THREAD

**Issue by ersatyle** [winadminsdotorg/SystemCenterConfigMgr#28]
from what I saw upon failure the script creating the zipped log file doesn't add the computername
fix is to modify CopyOSDLogs.ps1
$ComputerNameVariable = "OSDComputerName" 
To
$ComputerNameVariable = "_SMSTSMachineName"

https://gallery.technet.microsoft.com/Script-to-Zip-and-copy-c37c4c8e/view/Discussions#content
Written March 09, 2017
Johan Schrewelius
“OSDComputerName” is a commonly (MDT for example) used variable name to hold the machine name in a managed scenario. However so, it’s not built-in nor stipulated in any fashion, hence the possibility to change variable in the config section.

Best solution (keeps script intact) would probably have been to change
 
$ComputerNameVariable = "OSDComputerName" 
To
$ComputerNameVariable = "_SMSTSMachineName"

I will probably update the script so it falls back to the built-in variable in case the configured is missing or empty.

**Comment by Ebag333** [comment]
Really there should be some checking to see which one properly has it (isn't MININT), and use that one.

It could be either.

**Comment by Ebag333** [comment]
We grab the TSVars, so closing.
